version: 0.2

phases:
  install:
    commands:
      - echo installing maven...
      - yum install -y maven 
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean install -f java-tomcat-sample/pom.xml

artifacts:
  files:
    - '**/*.war'
